### ISSUE TITLE
Use OpenCV from a custom location

### ISSUE THREAD

**Issue by classner** [r9y9/OpenCV.jl#8]
Hi!

Thanks for creating this wrapper! In two settings it may be interesting to bind against a non-system OpenCV:

* when not having root access on the machine,
* when the system-provided OpenCV is older, but required by other libraries.

Is it possible to bind to OpenCV in another location? If so, how? If not, how can this be implemented best?

Best!

**Comment by r9y9** [comment]
Yes, it's possible. You can ignore system-installed one(s) by:

```jl
julia> ENV["OPENCVJL_LIBRARY_IGNORE_PATH"] = "/usr/local/lib:/usr/lib/"
julia> Pkg.build("LibOpenCV")
```

It will try to build a fresh opencv into LibOpenCV/deps directory.  If you want to link against your custom installed opencv, there is no clean way to do that for now, but you can do it, e.g. on macOS, by:

```jl
export DYLD_LIBRARY_PATH=$HOME/cv/opencv/build/lib:$DYLD_LIBRARY_PATH
julia -e "Pkg.build("LibOpenCV")
```

**Comment by classner** [comment]
This is great and easy to use! Thanks a lot for the quick response!

I just checked again the docs and didn't find it, would maybe be handy to add.

**Comment by r9y9** [comment]
Yes, docs are really work in progress.
