### ISSUE TITLE
error: no member named 'ACCESS_READ' in namespace 'cv'

### ISSUE THREAD

**Issue by classner** [r9y9/OpenCV.jl#9]
Hi again!

I encounter problems when building this package with the automatically downloaded version of OpenCV as well as with a custom-build version of OpenCV. Independent of this, an issue with OpenCV 3.1 that is currently automatically downloaded exists with gcc 6.1 (the default compiler on Ubuntu 16.10), see also [here](https://github.com/opencv/opencv/issues/6517). It can be fixed either by using a newer version of the OpenCV repository where it has been resolved or by adding `-DENABLE_PRECOMPILED_HEADERS=OFF` to the CMake call.

After successfully building, I am getting a lot of errors running Pkg.test("OpenCV") of even just trying to use any module:

```
ERROR: LoadError: LoadError: A failure occured while parsing the function body
 in ParseFunctionStatementBody(::Cxx.ClangCompiler, ::Cxx.CppPtr{Cxx.CxxQualType{Cxx.CppBaseType{Symbol("clang::Decl
 in #CreateFunctionWithBody#50(::Array{Any,1}, ::Symbol, ::Int64, ::Int64, ::Function, ::Cxx.ClangCompiler, ::String
 in (::Cxx.#kw##CreateFunctionWithBody)(::Array{Any,1}, ::Cxx.#CreateFunctionWithBody, ::Cxx.ClangCompiler, ::String
 in cxxstr_impl(...) at /is/ps2/classner/.julia/v0.5/Cxx/src/cxxstr.jl:347
 in macro expansion; at /is/ps2/classner/.julia/v0.5/CVCore/src/const.jl:124 [inlined]
 in anonymous at ./<missing>:?
 in include_from_node1(::String) at ./loading.jl:488 (repeats 2 times)
 in eval(::Module, ::Any) at ./boot.jl:234
 in require(::Symbol) at ./loading.jl:415
```

The last of the compiler errors is `:2:5: error: no member named 'ACCESS_READ' in namespace 'cv'`. I am using standard Julia v0.5 with Cxx 0.2 (standard package). Any hints on this?

**Comment by r9y9** [comment]
It seems that it failed to load `opencv2/core.hpp`. Can you try the following code?

```jl
julia> using Cxx
julia> using LibOpenCV
julia> cxx"""#include <opencv2/core.hpp>"""
```

I would like to see the full error log message of this (I'm expecting that fails for you). Also please check that `Pkg.test("Cxx")` works correctly.

**Comment by classner** [comment]
The tests for Cxx pass flawlessly. I found out that the reason is that the system `opencv2/core.hpp` header is included instead of the installed one from the library. This is from an older version and should be the reason for it to break.

So the fix should be to give the include path of the custom OpenCV preference over the system one. What would be the most elegant way to do so?

**Comment by r9y9** [comment]
umm, `cxx"#include <header>"` seems like trying to include the system one first.  I may have to rewrite `cxx"#include <header>"` with `cxxinclude(abs_path_of_the_header)`, as in [this line](https://github.com/JuliaOpenCV/LibOpenCV.jl/blob/212b9af8d4a0568fd5ff105e79a5952f24b75d06/src/LibOpenCV.jl#L83). I'm not sure what the most elegant way to do that... I will have to investigate.

**Comment by classner** [comment]
Fixed this and cleaned it up (see [pull request](https://github.com/JuliaOpenCV/LibOpenCV.jl/pull/2)). The headers had to be included first as user includes, then system includes again. Works flawlessly, thank you for the great package!

**Comment by r9y9** [comment]
closed by https://github.com/JuliaOpenCV/LibOpenCV.jl/pull/2
